### ISSUE TITLE
The Resources are not found

### ISSUE THREAD

**Issue by eck4god** [eck4god/BibleApp#20]
Resources are not being found when program is downloaded.

![Image](https://github.com/eck4god/BibleApp/assets/86024667/b7c09ae5-c9a4-43e7-9566-96f381fee975)

**Comment by khagenbaro** [comment]
I was also facing the same problem. so in my case i have solved the issue giving the full path name.
so it look like 
"/Users/khaegenm1/Projects/open-source-projects/bible-reader/bibleapp/resources/config.json"

**Comment by khagenbaro** [comment]
inside the class welcomescreen  method createBackground is missing the path. so i have the path there and pushed. please check

**Comment by eck4god** [comment]
Did you make a branch and push the branch up. The main branch is locked as to prevent race conditions

**Comment by khagenbaro** [comment]
i have created a branch and pushed it

**Comment by eck4god** [comment]
I found it and merged it. Thank You for the good catch
